### ISSUE TITLE
Spring Cloud Gateway 最初级的 HTTP 反向代理配置

### ISSUE THREAD

**Issue by JasonWu73** [JasonWu73/Blog#176]
Java 代码：

```java
@Bean
public RouteLocator customRouteLocator(RouteLocatorBuilder builder) {
  return builder.routes()
      .route(r ->
          r.path("/v1/**")
              .filters(f -> f.stripPrefix(1))
          .uri("http://localhost:8080")
      )
      .build();
}
```

对应的配置文件：

```yaml
spring:
  cloud:
    gateway:
      routes:
        - id: prods
          uri: http://localhost:8080
          predicates:
            - Path=/v1/**
          filters:
            - StripPrefix=1
```
